import { ReactQueryProvider } from "@/lib/react-query-provider";
import { ReownProvider } from "@/lib/reown-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense, type PropsWithChildren } from "react";
import { Header } from "./header";
import { headers } from "next/headers";
//@ts-expect-error: cannot find module
import stylesheetUrl from "./globals.css?url";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <head>
        <link id="global-css" rel="stylesheet" href={stylesheetUrl} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <Header />
          <Suspense fallback={<h1>Loading...</h1>}>
            <ReownProvider
              cookiesPromise={headers().then((h) => h.get("cookie"))}
            >
              {children}
            </ReownProvider>
          </Suspense>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
